Repository MingInc/ming, pull requests merged in 2024-08, with the labels that each got.

#3 feat: added not found page
  frontend/package.json
  frontend/src/app/company/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/not-found.tsx
  frontend/src/app/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/components/Menus.tsx
  frontend/src/components/NavigationBar.tsx
  frontend/src/components/ui/BackgroundBeamsWithCollision.tsx
  frontend/src/components/ui/breadcrumb.tsx
  frontend/src/components/ui/compare.tsx
  frontend/src/components/ui/cover.tsx
  frontend/src/components/ui/sparkles.tsx
  frontend/tailwind.config.ts
Labels: documentation

#4 doc: Fixed Footer
  frontend/src/app/company/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/not-found.tsx
  frontend/src/app/page.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/ui/compare.tsx
Labels: documentation, enhancement

#5 doc: added contents for Navbar
  frontend/src/app/company/page.tsx
  frontend/src/components/Menus.tsx
  frontend/src/components/NavigationBar.tsx
Labels: documentation, enhancement

#6 Minor Updates
  frontend/src/app/not-found.tsx
  frontend/src/app/page.tsx
  frontend/src/components/Menus.tsx
  frontend/src/components/NavigationBar.tsx
Labels: documentation, enhancement

#7 📃 docs: navbar content added, left to add links
  frontend/src/app/company/page.tsx
  frontend/src/components/Menus.tsx
  frontend/src/components/NavigationBar.tsx
Labels: documentation

#11 Update README.md
  README.md
Labels: Update

#8 auth: user registration completed, left for dashboard redirection
  frontend/.env.example
  frontend/package.json
  frontend/src/app/layout.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/components/Menus.tsx
  frontend/src/components/NavigationBar.tsx
  frontend/src/components/ui/avatar.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/popover.tsx
  frontend/src/components/ui/sonner.tsx
  frontend/src/components/ui/sparkles.tsx
  frontend/src/firebase.config.ts
Labels: documentation, enhancement

#12 Auth
  backend/client/.gitignore
  backend/client/README.md
  backend/client/eslint.config.js
  backend/client/index.html
  backend/client/package.json
  backend/client/public/vite.svg
  backend/client/src/App.css
  backend/client/src/App.tsx
  backend/client/src/assets/react.svg
  backend/client/src/index.css
  backend/client/src/main.tsx
  backend/client/src/vite-env.d.ts
  backend/client/tsconfig.app.json
  backend/client/tsconfig.json
  backend/client/tsconfig.node.json
  backend/client/vite.config.ts
  frontend/package.json
  frontend/src/app/company/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/profile/page.tsx
  frontend/src/components/NavigationBar.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/chart.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/components/ui/sheet.tsx
  frontend/src/components/ui/table.tsx
Labels: documentation

#14 Fixing ESLint Issues
  frontend/src/components/Navbar.tsx
  frontend/src/contexts/AuthContext.tsx
  frontend/src/index.css
Labels: documentation, enhancement, good first issue

#15 Fixing ESLint Issue
  frontend/src/contexts/AuthContext.tsx
  frontend/src/pages/Login.tsx
  frontend/tsconfig.json
Labels: documentation, enhancement, good first issue

#17 Template Card with framer motion added.
  frontend/package.json
  frontend/src/components/TemplateCard.tsx
  frontend/src/components/blocks/expandable-card-demo-grid.tsx
  frontend/src/components/blocks/expandable-card-demo-standard.tsx
  frontend/src/components/ui/accordion.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/hooks/use-outside-click.ts
  frontend/src/pages/Projects.tsx
  frontend/vercel.json
Labels: documentation, enhancement, Update

#18 fix: Updated vercel.json
  frontend/vercel.json
Labels: documentation

#19 fixed build issue
  frontend/src/components/blocks/expandable-card-demo-grid.tsx
Labels: good first issue

#20 Working on minor fixes
  frontend/src/components/blocks/expandable-card-demo-grid.tsx
  frontend/src/components/blocks/expandable-card-demo-standard.tsx
Labels: documentation, enhancement, good first issue

#21 Edited Template Card
  frontend/src/components/TemplateCard.tsx
  frontend/src/pages/Projects.tsx
Labels: documentation, enhancement

#23 page: home page updated with resposive login button
  frontend/src/pages/Home.tsx
  frontend/src/pages/Login.tsx
Labels: documentation, enhancement

#24 Working on JS Framework Deployment
  backend/.gitignore
  backend/README.md
  backend/controllers/DeployProject.ts
  backend/helpers/CorsHeader.ts
  backend/index.js
  backend/index.ts
  backend/package.json
  backend/scripts/DeployProject.sh
  backend/tsconfig.json
  frontend/package.json
  frontend/src/components/TemplateCard.tsx
  frontend/src/components/ui/toast.tsx
  frontend/src/components/ui/toaster.tsx
  frontend/src/components/ui/use-toast.ts
  frontend/src/main.tsx
  frontend/src/pages/Projects.tsx
Labels: documentation, enhancement

#26 fix:next speed insights was used insted of React
  frontend/src/main.tsx
Labels: good first issue, invalid

#28 Create SECURITY.md
  SECURITY.md
Labels: documentation, Update

#29 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#27 fix:random uid named container, still need to work on whole project d…
  backend/.dockerignore
  backend/Dockerfile
  backend/controllers/DeployProject.ts
  backend/helpers/RandomGenerator.ts
  backend/helpers/StringManipulations.ts
  backend/scripts/DeployProject.bat
  backend/scripts/DeployProject.sh
Labels: documentation, enhancement, help wanted
